version: "3"

services:
    client:
        image: kidneybot
        volumes:
            - ./logs:/app/logs
            - ./config.json:/app/config.json
            - ./database-backups:/app/utils/database-backup-util/backup
        restart: unless-stopped
