[tool.poetry]
name = "kidney-bot"
version = "0.1.0"
description = ""
authors = ["Alec Jensen <alecbradyjensen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiohttp = ">=3.9.0,<3.10.0"
discord = ">=2.3.2,<2.4.0"
psutil = "^5.9.6"
motor = ">=3.3.2,<3.4.0"
pynacl = "^1.5.0"
requests = "^2.31.0"
google-api-python-client = "^2.111.0"
synonym = "^0.1.3"
shakespeare-insult = "^1.0.3"
wikipedia = "^1.4.0"
faker = "^21.0.0"
humanize = "^4.9.0"
typing-extensions = "^4.9.0"
pafy = {git = "https://github.com/alec-jensen/pafy.git", rev = "develop"}
pilcord = {git = "https://github.com/alec-jensen/pilcord.git", rev = "main"}
youtube-dl = {git = "https://github.com/ytdl-org/youtube-dl.git", rev = "master"}
toml = "^0.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
